apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169646658
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169646658
    app.kubernetes.io/part-of: test-app-169646658
  name: python-basic-169646658
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169646658
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169646658
    spec:
      containers:
      - image: quay.io/hacdev/rdkfzkll-tenant/test-app-169646658/python-basic-169646658@sha256:518bdf826160b4b88a2bbd41bc7de273876dde5cb0211ceb40d0e17f955676a5
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
